import type { Metadata } from "next"
import { Inter } from "next/font/google"

import "@/styles/globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Chat bot",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="bg-[#E5E5E5]    w-full   h-screen">
        <main className=" bg-[#E5E5E5] px-3  border max-w-[54rem] m-auto  flex items-center justify-center md:justify-start  font-manrope">
          {children}
        </main>
      </body>
    </html>
  )
}
