import type { Metadata } from "next"
import { Inter } from "next/font/google"

import "@/styles/globals.css"
import Demo from "./dashboard-components/Demo"
import Header from "./dashboard-components/Header"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Chat bot",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="">
        <main>
          <div className=" mx-0 md:mx-32 lg:mx-40">
            <Demo>{children}</Demo>
          </div>
        </main>
      </body>
    </html>
  )
}
