import type { Metadata } from "next"

import "@/styles/globals.css"
import Container from "./dashboard-components/Container"
import AppProvider from "@/app/context/AppContext"
import { ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.css"


export const metadata: Metadata = {
  title: "Chat bot",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="">
     
        <main>
          <AppProvider>
            <div className="lg:mx-32 xl:mx-40 mx-0 ">
              <Container>{children}</Container>
            </div>
          </AppProvider>
        </main>
        <ToastContainer />
    
      </body>
    </html>
  )
}
